#+STARTUP: overview

* Declarative Languages for web:
** CSS FUNDAMENTALS
Need some kind of review of CSS;
it's an entire rabbit hole unto itself...
*** Class attributes:
Apparently, more than one class attribute can be assigned to
an HTML page element, as in:
<li class="cell cell01"></li>
defining a "list item" element with class attributes of "cell" and "cell01"?
** HTML FUNDAMENTALS
Yet another rabbit hole...


* Procedural Languages for web:

** Microsoft dotNet stuff:

*** dotnet web core v8

**** asp.net core v8
[2024-11-04 Mon 13:53]
This seems to hinge around the "portable/ported" flavor of the dotNet
system, dotnet core v8.

There's a "default web server" buried in the middle of this thing,
called kestrel, and I'll bet that it is kestrel which is used,
behind nginx, when running on a k8s cluster/pod?

kestrel in a containerized application, right?

There's a "dotnet cli" system, which is kind of like "Vite" in the
React/node world:  it's a cli application runnable from Linux which
lets you build out a start to an application with a short CLI command;
this lets you build out various kinds of dotnet applications quickly...

**** installation and setup

***** debian-linux-under-wsl2
https://learn.microsoft.com/en-us/dotnet/core/install/linux

The wget2 command should be used instead of wget:
  wget2 https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  sudo dpkg -i packages-microsoft-prod.deb
  rm packages-microsoft-prod.deb

I used the aptitude terminal tool to:
+ update the packages-available information (this updated the indexes, etc, with
  the info from packages.microsoft.com)
+ install dotnet-sdk-8.0
+ I had to later run:
    dotnet workload update
  because I was instructed to do so by the output from:
    dotnet new console --help --language F#
  

And this should have set up the dotnet sdk cli tools for
me, right?


***** debian linux and emacs lsp setups
It's nice to have intellisense/autocompletion options available
in Emacs, and tools mentioned here make that possible.
There are LSP-related tools for all kinds of programming
languages that you can set up for Emacs to use.

****** install or update jsonrpc package!

****** install the lsp-mode

****** install fsharp-mode 

****** Is there a mode needed for typescript?
There is a typescript langugage server provided via npm,
and installation of that into the "global" nodejs setup seems
to make it accessible, if you start up the lsp-mode in a
node project's folder (which'll container folders of node-ish
stuff that should be reachable by tools?)

***** VScode for Linux
[2024-11-06 Wed 20:48] I wanted to set up VScode in Linux,
inside of WSL2, to use it directly there, and wanted to see if
I could get it up-and-running to let me edit F#, C#, and
TypeScript code.




** JavaScript
*** modules
**** import-ing
**** export-ing
*** var, let, const and variable scopes
**** var means it's a "global" scope variable
**** let means it's a "local-to-enclosing-block" variable
**** MOST of the time you want to use let 
***** certainly when it's a variable local-to-a-block
***** Use it in the "global" scope when you'd like to redefine it?
NO:  actually, a "let" used at the "top" level is fundamentally
equivalent to use of "var" correct?
**** scope control for variables
**** variable "hoisting"
Refers to the "legality" and "presence" of a variable
being pushed to the top of its enclosing program block;
https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#variable_hoisting
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#function_hoisting

I seem to recall people talking about "hoisting" in
terms of "function hoisting," in which the identifier
gets "pushed" or "hoisted" up to the "top," when the
identifier names a *function*.  On the other hand,
*variable hoisting* seems to be different affair
entirely.

The use of the term "hoisting" seems to be a particular
artifact of the JavaScript programming language design.
Other languages are much more straightforward, and
issues of identifier scope are simpler.

Note:  from the top of an enclosing block, until the
declaration of a block-level variable, the variable's
value is "undefined," even though the variable exists.
(Got that?)  Attempts to use the variable in the
program block 
See also:  "temporal dead zone."
**** "temporal dead zone"
Refers to the subprogram space between the start of an enclosing
block and the definition of a variable (via declaration?)
and in which the variable can't legally be used in a program,
btw you're not even allowed to try and compare the variable to
"undefined" in the "temporal dead zone!"
***** EXAMPLE
The following:
  var myFifteen = 15;

  { let myFifteen = 14; console.log(myFifteen); }

  { console.log(myFifteen); let myFifteen = 14 }

  console.log(myFifteen);
results in:
  14
  Uncaught ReferenceError: Cannot access 'myFifteen' before initialization
because we don't even get to the final console.log(myFifteen) because
the second block results in that "Uncaught ReferenceError."
So, no use of variables which haven't been declared yet, even to
see if they're 'undefined...'

However:
  var myFifteen=15;
  { let fcn = function () {console.log(myFifteen);}; let myFifteen=14; fcn(); }
  console.log(myFifteen)
results in:
  14
  15
because that block's call to its locally-defined function, bound to
the name "fcn", uses the local-to-block instance of the variable myFifteen,
which is bound to the value 14 by the let-assignment, and by the time
the function-named-by-fcn is invoked, that let-binding is in effect.

And this completes without an uncaught ReferenceError:
  var myFifteen=15;
  { let myFifteen; let fcn = function() {console.log(myFifteen);};
    if (myFifteen == undefined) console.log("It's undefined!"); else console.log(myFifteen) ;
    myFifteen=14; fcn(); }
  console.log(myFifteen)
Its output:
  It's undefined!
  14
  15

*** comparison operators
i.e., == versus =​=​=
**** AN EMACS ORG-MODE NOTE:
(N.B. there is a non-breaking space, 200B, between
those final two equal-signs...
inserted via:
  C-x 8 <RET> 200B <RET>
It seems, after looking at it with hexl-mode, that there's
further encoding done of "0x200b" into something else,
because I do NOT see a sequence of 0B20 or something of
the sort inside the hexl-mode view of this file!
This is necessary because in org mode, a double-equals sign
delimits something which should be rendered as bold-face text
or some such...)

**** the difference between the two:
<A> =​= <B> is, roughly,
"see if <A> evaluates to something equal to what <B> evaluates into,
given JavaScript's peculiar variable and equality rules."

While the =​== is, roughly,
"see if <A> =​= <B> and also if <A> and <B> are the same type."
(what ever "type" means in Javascript...)

So, for example:
  14 =​= "14"
is true, but
  14 =​=​= "14"
is false.

*** objects
More like "structures" or "records" or like Python's "dictionary"
*** classes
**** inheritance
**** overriding?
Does Javascript provide dynamic dispatch for overridden methods?
It seems this is possible, but the introductory course doesn't
really talk much about it such issues.
*** DOM changes via JavaScript
**** Emphases in Morten Rand-Hendricksen JavaScript Course:
***** DOM-manipulation
The Morten Rand-Hendricksen course on JavaScript did lots to
fiddle with the styles assigned to individual page elements by
simply mutating via assignments like:
  <element-item>.style.<style-attribute> = <some-value>;
and other such mutations.
***** iteration:
Iteration over collections of page elements fetched via
  document.querySelectorAll('<CSS-STYLE-SPECIFICATION>')
(or the querySelector method, also)
was often shown to demonstrate how to walk through a pile of
stuff on a page and change how it looks.  This was a mechanism
to allow one to find everything on the page which meets certain
criteria, and changing it in specified ways.  When we have
decided ahead of time that a certain set of page elements should
have certain styles, this gives us a way to manipulate a set
of page elements as a unit...
**** document.querySelector
**** document.querySelectorAll('<STYLE-SPECIFICATION>')
What ain't terribly clear is how to write the <STYLE-SPECIFICATION>, eh?
**** iterating over DOM elements seems to be a recurring theme!
*** Array methods
**** map
**** reduce


*** Peculiar:  Destructuring assignment

**** Particular examples are shown in
09_05/script.js saved in the main-personal branch.
**** One example
An example:
let myObject = { first: 'firstval', key : 14, active: false };
// And now, within the scope of a function, we "pull out" the elements/properties
// of myObject, which is accessible from within the function body:
(function() {
  let {first: first , active: active} = myObject;
  // And now, inside this function,
  // identifier
  //   first
  // is bound to
  //   myObject.first
  // and myObject.first == 'firstval',
  // and also, identifier
  //   active
  // is bound to myObject.active.
  //
  console.log(`${first} , ${active}`)
 } ) ();
// This outputs to console:
//   firstval , false
*** setting up NPM for use on your workstation
see file runtime-setup-notes.txt
*** node-ecosystem
**** package.json
[2024-10-03 Thu 15:40] returned to the second nodejs course (Porcello, on
LinkedIn Learning...)
There's quite a bit there about the package.json file, and it lets
you specify what modules your node project depends on.
Commands like
  npm install
govern this, and the package.json lets you automatically fetch
what is specified in the package.json under the key "dependencies"...

Apparently, it's possible to have a "devDependencies" key also,
to specify what you need ONLY for "development use," and such
things will not ordinarily be installed/fetched when doing a
"production" setup?

Ordinarily, the installed packages will end up in the project
folder's node_modules folder, right?  This makes its changes,
the goop it brings in from the glorious repository-of-all-nodeness,
locally-scoped to just your project, unless you specify that
you want such packages installed *globally* using
  npm install -g <MODULE_NAME>
***** scripts key
The "scripts" key lets you name-value-pair a shell script
command to be invoked via npm;
for example, a "scripts"-value pair might look like:
  ...
  "scripts": {
    "start": "node index --time 14"
  },
  ...
would let you run "npm start" from the command line and
the shell script corresponding to package.json key "start"
would be run on your behalf.  In this case the command
  node index --time 14
would be executed on your behalf.

N.B. "start" is an exceptional key name; a script with any
key other than "start" must be used by:
  npm run <KEY>

**** npm commands
***** GENERAL NOTE:
+ using --save-dev or -save-dev command line flag will cause
  npm to set up development-time-only packages;
+ as noted elsewhere, the -g flag causes npm to install the
  package "globally," into the package folder shared across
  all projects, instead of installing into the local project's
  folder structure.
+ the '@<MAJOR>.<MINOR>.<PATCH>' notation lets you specify after
  a package-name the major, minor, and patch numbers for the package,
  which lets you fine-tune which version of a particular package
  you wish to install/update/uninstall, it seems


***** npx command
npx -p <PACKAGE_NAME> ...

e.g.,
  npx --p @angular/cli ng new myapp
would set up an angular project in folder ./myapp without
cramming all of the stuff associated with angular development
into your machine, apparently...

And package.json scripts can take advantage of the npx
approach, too!

See more documentation:  https://www.npmjs.com/package/npx



***** npm SCRIPTING:
+ link:
    https://docs.npmjs.com/cli/v9/using-npm/scripts
+ set up scripts to run from your package.json file...

***** CACHE COMMANDS

****** npm cache verify

****** npm cache clean -force
forces a cache cleanup;  helpful for troubleshooting

***** npm audit
only for npm version 6 and above;
provides detailed report on current vulnerabilities and issues with the
current project;


***** npm outdated
will give a report of those packages which are "outdated" so that
you might be able to run "npm update" to bring them up to date...

***** npm install
Will install all of the packages specified in the package.json
"control file" (and this allows one to quickly set up a project
which might've been checked out of source control, let's say...)
***** npm install <MODULE-NAME>
Installs a particular module, and automatically makes entries
into the package.json, right?  Switches like "-g" let you
install the package into the "global" location on your machine,
in case you want the package to be available for all nodejs
use (which is done for things like compilers, etc...)

It seems that *ordinarily* you won't do this when doing most
development work.
***** npm uninstall
***** npm ls
This lists the packages/modules that are in the current project's
setup, i.e., in the current project's accessible node_modules
folder, which is ./node_modules

Now,
  npm ls -g
shows what is installed at the "global level" for the entire
system, right?  This is all of the stuff "globally available..."

Variations:
  npm ll
gives a longer-listing, more-detailed list of packages installed.

The nodejs runtime tends to "crawl up and down" the directory
structure, I think, and it knows where to look for things based
on the package.json, amongst other things?

***** npm run <KEY>
Lets you run the scripts stored under <KEY> in the "scripts"
part of the package.json structure;
if the <KEY> is "start" then you can just run the "start"
script with
  npm start
but otherwise you must explicitly use "npm run"...

***** npm exec <PACKAGE-NAME>?
[2024-11-06 Wed 20:53] I was able to run the locally-installed
local-web-server package and start serving node project stuff
immediately:
  npm exec local-web-server
but note I needed to have the local-web-server installed into
the local node-project folder hierarchy already:
  rstewar@IMLADRIS:~/node-work/js-and-ts-exercises/Ex_Files_JavaScript_Async_2021/Exercise Files/Ch02/02_06/begin/_scripts
  $ npm ll
  js_async_exercises@1.0.0
  | /home/rstewar/node-work/js-and-ts-exercises/Ex_Files_JavaScript_Async_2021
  | Exercises in Asynchronous JavaScript/TypeScript; we want to use a local-server to increase instructional value.
  `-- local-web-server@5.4.0

***** npm prune
Will remove any of the modules/packages presently installed
but which are not mentioned in the packages.json
"dependencies" structure.

So, it's possible to edit the "dependencies" in the package.json
and run "npm prune" etc...


**** npx commands

***** npx live-server --no-browser .
will let you serve up basic stuff from within the entire "project tree."

***** node <JAVASCRIPT-PROGRAM-FILENAME>
very primitive/elementary way to get something started
from the command-line; used lots in the LinkedIn Learning
Eve Porcello Node.js course on building elementary Node.js
applications.

**** nvm and node 20
[2024-11-06 Wed 16:39] I installed nvm into Debian WSL2 instance
DebianWork by doing the following.  This was done in ordert to
get node v20 set up inside of my Debian instance:

I followed the instructions at:
  https://nodejs.org/en/download/package-manager
but the instructions were not perfect, because the url
  https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh
did not actually fetch anything.  Fortunately, I was able to get
to the github repo in:
  https://github.com/nvm-sh/nvm
and find the nvm v0.40.0 installation script, and I fetched it
with:
  curl -o nvm-0.40.0-install.sh https://github.com/nvm-sh/nvm/releases/v0.40.0/install.sh
and then ran it from a bash prompt after "chmod u+x"...

Here is the output it made:
  rstewar@IMLADRIS:~
  $ ./nvm-0.40.0-install.sh
  => Downloading nvm from git to '/home/rstewar/.nvm'
  => Cloning into '/home/rstewar/.nvm'...
  remote: Enumerating objects: 380, done.
  remote: Counting objects: 100% (380/380), done.
  remote: Compressing objects: 100% (323/323), done.
  remote: Total 380 (delta 43), reused 175 (delta 29), pack-reused 0 (from 0)
  Receiving objects: 100% (380/380), 382.20 KiB | 2.56 MiB/s, done.
  Resolving deltas: 100% (43/43), done.
  * (HEAD detached at FETCH_HEAD)
    master
  => Compressing and cleaning up git repository

  => Appending nvm source string to /home/rstewar/.bashrc
  => Appending bash_completion source string to /home/rstewar/.bashrc
  => You currently have modules installed globally with `npm`. These will no
  => longer be linked to the active version of Node when you install a new node
  => with `nvm`; and they may (depending on how you construct your `$PATH`)
  => override the binaries of modules installed with `nvm`:

  /usr/local/lib
  +-- typescript-language-server@4.3.3
  `-- typescript@5.6.2
  => If you wish to uninstall them at a later point (or re-install them under your
  => `nvm` Nodes), you can remove them from the system Node as follows:

       $ nvm use system
       $ npm uninstall -g a_module

  => Close and reopen your terminal to start using nvm or run the following to use it now:

  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

Indeed, I see that:
  rstewar@IMLADRIS:~
  $ npm ll -g
  /usr/local/lib
  |
  +-- typescript-language-server@4.3.3
  |   Language Server Protocol (LSP) implementation for TypeScript using tsserver
  `-- typescript@5.6.2
      TypeScript is a language for application scale JavaScript development

I will go ahead and try to keep them around, and then see if I can still
edit TypeScript actively with Emacs after I update my local node to
a flavor of node 20:

I started up a new tmux "window" and then tried the rest of the commands
on that nodejs.org instruction list:
  rstewar@IMLADRIS:~
  $ nvm install 20
  Downloading and installing node v20.18.0...
  Downloading https://nodejs.org/dist/v20.18.0/node-v20.18.0-linux-x64.tar.xz...
  ########################################################################################################################################################################################################################### 100.0%Computing checksum with sha256sum
  Checksums matched!
  Now using node v20.18.0 (npm v10.8.2)
  Creating default alias: default -> 20 (-> v20.18.0)

Now, I see that, in the "fresh login," that I will need to install
into the new "node installation," for I don't have the typescript
language server anymore:
  rstewar@IMLADRIS:~
  $ npm ll -g
  /home/rstewar/.nvm/versions/node/v20.18.0/lib
  |
  +-- corepack@0.29.3
  |
  `-- npm@10.8.2
      a package manager for JavaScript

So:
  rstewar@IMLADRIS:~
  $ npm install typescript-language-server -g

  added 1 package in 5s
  rstewar@IMLADRIS:~
  $ npm ll -g
  /home/rstewar/.nvm/versions/node/v20.18.0/lib
  |
  +-- corepack@0.29.3
  |
  +-- npm@10.8.2
  |   a package manager for JavaScript
  `-- typescript-language-server@4.3.3
      Language Server Protocol (LSP) implementation for TypeScript using tsserver

And then:
  rstewar@IMLADRIS:~
  $ npm install typescript -g

  added 1 package in 6s
  rstewar@IMLADRIS:~
  $ npm ll -g
  /home/rstewar/.nvm/versions/node/v20.18.0/lib
  |
  +-- corepack@0.29.3
  |
  +-- npm@10.8.2
  |   a package manager for JavaScript
  +-- typescript-language-server@4.3.3
  |   Language Server Protocol (LSP) implementation for TypeScript using tsserver
  `-- typescript@5.6.3
      TypeScript is a language for application scale JavaScript development
  
And that seems to allow me to continue working with the TypeScript compiler,
and the TypeScript language server, under Emacs,
AND
work with a later incarnation of Node.js server-piece.

sigh.

** TypeScript

*** Emacs as TypeScript IDE

+ installed lsp-mode package
  M-x package-install RET lsp-mode RET
+ I *think* I updated the lsp-mode package, or else uninstalled it first
  in order to get the most recent version.
+ I installed, next:
  + M-x package-install RET lsp-ui RET
  + M-x package-install RET flycheck RET
  + M-x package-install RET company-mode RET
  + M-x package-install RET lsp-treemacs RET
+ For typescript support, I set up the typescript language LSP stuff that runs
  under node-js:
  + M-x lsp-install-server RET ts-ls RET
+ Elisp expressions to use after opening that first ".ts" file:
  + M-x lsp-mode
    (starts up the language server and all of the other major pieces
    to give nice completion and on-the-fly highlighting of errors, etc)
  + M-x lsp-treemacs-errors-list
    (pops up a tree-structured list of current errors, in the pane below.)
  + M-x lsp-treemacs-symbols
    (creates tree-structured list of the program symbols in the pane to the left.)
+ There are many features best accessed via right-clicking on the
  various program identifiers and picking from a menu.  Many of them
  can be invoked via "super-key" key combinations, but since there is not
  a convenient "super-key" modifier key on my keyboard, the best we can
  do is to "C-x @ s" before the key.  Thus, "s-l" is "C-x @ s l" and a bunch
  of features are invoked as options to the "s-l"/"C-x @ s l" keyboard prefix;
  you can see them next to their menu options in the right-click menu that
  pops up.
+ SYNTAX HIGHLIGHTING:
  + I also ended up installing the typescript-mode major-mode package,
    which provided the syntax highlighting we see in things like VSCode.
    Turn on typescript-mode, then turn on lsp-mode, and all is well, it
    seems:  the lsp-based services work nicely to give you an Emacs version
    of many of the niceties of using VSCode.
  + There's nice package-management GUI stuff, but it's probably also
    just as easy to run:
      M-x package-install RET typescript-mode RET
  

*** This is mandated by Oracle web stuff nowadays!

*** TypeScript Essentials LinkedIn Learning Notes

**** installation

***** Install at the "project level"
This sets it up as a "dev dependency" so that it does not
end up installed "globally for the entire machine,"
and allows you to change to different flavors/versions of
typescript for each distinct project.  Installing as a
"dev dependency" also means that typescript will only be
needed at development time, and not used by your application
at runtime:
  npm install typescript --save-dev
If you want it installed for the "entire machine," or
"globally" then use the command:
  npm install typescript -g

Therefore, I may need to execute the
  npm install typescript --save-dev
for each lesson folder in the LinkedIn course?

***** Special note on use for the LinkedIn course:
I installed the typescript system at the top of the
repo cloned from the instructor, which is 3 hops above
the individual exercise file directory.  That is, in
the top-level folder of the repository, I used:
  npm install typescript --save-dev
and from there, I could change to subordinate folder
  cd exercise_files/Ch01/01_03b
and execute:
  npx tsc
and it should build things appropriately.  One may use the
--listFilesOnly option for the typescript compiler and
have it vomit out all of the files it examines in order
to do a "build," which is useful when trying to
troubleshoot what the course materials are doing.

What's more, the instructor is fond of shutting OFF the
"emitting javascript" option so that no new output files are
generated, via a tsconfig.json file, and so that "noEmit"
in the compilerOptions of the tsconfig.json file may need
to be fiddled with also.

***** How to pull out type information
The --declaration command-line argument to the compiler
is one way to see the types the compiler has assigned
to program objects.


**** How types are used in TypeScript:
***** type declarations
Like so:
  let <VAR0> : <TYPE0>
and also in function signatures:
  function exampleFunc(param1 : <TYPE1>,...) : <TYPEn> { ... }

See also:  "generics"


***** type "casting"
You may force an assignment to a (strongly-)typed variable
by using the "as" operator on the object in the RHS of the
assignment; for example:
  let x : string[];

  x = "Hello!" as any;
Tells the compiler to ignore the type of x.

Probably useful for troubleshooting; bad in practice, for
over-use means you've abandoned one of the reasons for
using TypeScript in the first place.


***** interfaces
An "interface" is declared like so:
  interface AnInterface {
    <MEMBER0> : <TYPE0> [,;]
    <MEMBER1> : <TYPE1> [,;]
    ...
  }
And thusly AnInterface becomes a type name that can be
used in type declarations, function/method return types,
in their signatures, etc.

***** generics
Generics in declarations kind of follow the C++/Java/C# kind of
notation, with, in general, multiple type-parameters enclosed in
"<>" pairs.  And one may "constrain" a type with extends syntax,
as in the following, where general type parameters are all-caps,
and where other type names are "general," etc:
  function
    myFunction<TYPE1, TYPE2 extends TYPEn>
      (p1 : numberOrSomething, p2 : TYPE1, ...) : returnType
  { ... }

***** type aliases
e.g.,
  type ContactName = string;
simply a shortcut...


**** Importing third-party types
This is extremely useful if you want to use a third-party
Javascript library in a TypeScript system;
There is usually a way to get TypeScript type definitions
for a JavaScript library or Node.js Package you wish to use,
right?

a library which doesn't offer typescript support:
you may have to get the compiler to emit the ".d.ts" files
and then start modifying them with more explicit type
definitions, no?

Otherwise, you can find type definitions from
  github.com/DefinitelyTyped/DefinitelyTyped
AND
all of the folders there are published as packages
via the @types "pseudo-folder" inside npm.org, eh?

So, you can often do something like
  npm install @types/<SOME_PACKAGE>
to get the types set up for <SOME_PACKAGE>


**** Esoteric Features
***** Union types 

****** A kind of discriminated union?
another example:
  type ContactBirthDate = Date | number | string
this is a "union type" which specifies that ContactBirthDate
may be one of three distinct types.  These are *alternatives*,
different options.

So, a ContractBirthDate-typed program object is a member of
the set which is the UNION of the set of Date's, number's, string's...

****** attribute unions:  type "extensions/additions"
There's also a way to bring together two distinct types
together:
  interface Contact  {
      id: number;
      name: ContactName;
      birthDate?: ContactBirthDate;
      status?: ContactStatus;
  }

  interface Address {
      line1: string;
      line2: string;
      province: string;
      region: string;
      postalCode: string;
  }

  type AddressableContact = Contact & Address

So, I suppose that the "set of things" in
  keyof AddressableContact
is the union of the two sets:
  keyof Contact
  AND
  keyof Address

****** alternative to "enum"
In an alternative to "enum's" :
  type ContactStatus = "active" | "inactive" | "new"
means that something declared as type ContactStatus
can be a string variable which is restricted to
the three values "active", "inactive", "new".

This can be shorter than:
  enum ContactStatus {
      Active = "active",
      Inactive = "inactive",
      New = "new"
  }



***** typeof operator
This seems to be general JavaScript
AND
TypeScript extends its use to its "structural types,"
so that it's possible to specify all kinds of type specifications
with it.  We may specify that a variable must be the same type
as the type of another variable, as in:
  let myType = { min: 1, max; 200 }

  function save(source: typeof myType) {...}

***** keyof operator
One can construct "types" which are based on the "key values"
available in an "object-type" (basically a record-object?).

E.g., given:
  type ContactName = string;
  type ContactStatus = "active" | "inactive" | "new"
  type ContactBirthDate = Date | number | string

  interface Contact {
      id: number;
      name: ContactName;
      birthDate?: ContactBirthDate;
      status?: ContactStatus;
  }
we may define a type which is "the set of fields of Contact":
  type ContactFields = keyof Contact

And it's possible to use this in interesting, general ways
in type-parameters used to define generic functions:
  function getValue <T, U extends keyof T>(source:T, propertyName: U){
      return source[propertyName]
  }
Notice that "U extends keyof T" as one of the type parameters:
it's possible to constrain type parameters to be constrained by
a type "keyof <TYPEx>" 
  
***** Specifying Object types

****** Index signatures
From typescriptlang.org's TypeScript Handbook:
  interface StringArray {
    [index: number]: string;
  }

  const myArray: StringArray = getStringArray()
  const secondItem = myArray[1];

So, secondItem is a string-typed variable.
StringArray is a kind of JavaScript object which is
indexed with number's, and which contains string's.

They call that
  [index: number]
part the "index signature" part of the type signature/spec?

This is the way one specifies that the StringArray-typed
object can be accessed using the "indexing" notation in
a program.

It's also possible to add other fields/properties, too:
  interface myIntfc {
    [index: number] : number;
    prop1 : number
  }

N.B. THERE IS A BIG DIFFERENCE BETWEEN INDEX SIGNATURES
NOTATION IN type/interface DECLARATIONS, AND THE USE
OF THE []-BRACKETS IN GENERIC TYPE SPEC/DECLARATION!!!

Another example:
  type myIntfc = {
    // the following is meant to specify how accessing
    // a myIntfc by index notation should work, type-wise:
    [index: number] : string;
    // This is a more ordinary specification of a property
    // "prop1" which has type "number":
    prop1 : number
  }

  let v3 : myIntfc = { prop1 : 4 }
  v3[0] = "jack"
  console.log(v3[0])
  console.log(v3["prop1"])
  console.log(v3)
Should output:
  jack
  4
  { '0': 'jack', prop1: 4 }


****** Mapped types
From the documentation site:
"A mapped type is a generic type which uses a union of PropertyKey's
(frequently created via keyof) to interate through keys to
create a type..."

The fundamental idea of a mapped type seems to be very
JavaScript-oriented:  this allows us to specify a general
quantification over all of the "keys"/attributes of a type
(specified as a type parameter) derive a new type with the
same attributes, but with types whose structure is a function
of the original type-and-attribute-set.

For example:
  interface Item {
    name : string;
    age : number;
  }

  type QType2<ItmType> =
    { [TProp in keyof ItmType]? : (v : ItmType[TProp]) => boolean;
      ["ephemeral"|"something"] : (v : ItmType) => null }
  let v1 : QType2<Item> =
    { name : (v : string) => false, age : (v : number) => false }
  


***** TODO Indexed access types
Use index access notation:
  type Awesome = Contact["id"]
This specifies that Awesome is of the same type as
the type declared for the id propery of something that
is a Contact type/interface.

[2024-09-19 Thu 16:13] Need some notes here!

***** Utility Types
There are a bunch of parameterized/templated types
which were added to help with a lot of things.
****** TODO Record types
The general syntax of a record lets you specify records
with fields, in order, of TYPE1, TYPE2, etc:
  Record< TYPE1, TYPE2...>

****** Partial type

****** 


**** How does Oracle make use of TypeScript in their stuff?

**** Do other teams in the organization use TypeScript strong-typing?


** Oracle JET needs 

*** TypeScript
*** Nodejs

*** NPM

*** Preact
Oracle made use of this and their JET documentation is
bifurcated into the "virtual DOM" and "MVVM" thinking...

* understanding Javascript for long-term in Oracle Cloud Fusion
Need to understand the rest of Javascript as quickly as possible, and then
get to where we understand how to use it to program with Oracle's JET?
Need to know if "Visual Builder" applications are actually node-based
applications which can be run inside a node application server,
and which can be run on something other than Oracle's infrastructure.

This ain't necessarily a bad thing, just a different thing.
But not being allowed to run SQL in the way which we used to
is going to be a major change for some folks on our team,
and could become a big hurdle to overcome.

* long-term thoughts about programming:
If there is some hope, it might lie with the Plato programming
language, by Christopher Diggins, and improved automation of the AEC
world-of-business-operations.

Architecture, Engineering, and Construction businesses need further
help, and Diggins, a former Microsoft guy, started a consultancy
to develop software and services for AEC firms.  Read more at:
  https://ara3d.com/ his firm's website
  https://github.com/cdiggins his github profile
Diggins designed a concatenative programming language called
Cat, which was forth-like language which also had type inference,
so it was a concatenative, strongly-typed, functional programming
language.



* WSL kind of sucks
WSL is barely adequate as a Linux environment:  there are
enought quirks and irregularities that one pines for a
standard, atop-the-metal Linux environment, in the best
of circumstances.  That is, even when the host Windows system
is not hobbled/encumbered with lots of extra mandated
"infrastructure/gunk," WSL has all kinds of problems.  The
only reasonable thing is that Microsoft is, to a degree,
"forced" to deal with its problems, even if the fix you
keenly need to deal with your particular vexing problem
seems to be low on Microsoft's priority list!

When Windows-underneath is further hobbled with inadequately-
configured "security-protections" (invasive things like
BeyondTrust and/or Crowdstrike) then WSL is just worse,
and the host Windows system is so terribly hobbled that
WSL can't work well:  for example, there isn't enough RAM
left to allow it to function well and operate properly.

This can tend to make WSL sound like a reasonable solution
to certain classes of problems, until the ugly reality of
severely curtailed and limited RAM kicks some teeth out
and one realizes that the imposed "security" solutions
render practical use of WSL impossible.



* miscellaneous thoughts
I would prefer to use a non-modal editor, frankly.  The Vi-way, which
is a modal editor scheme, is just terribly disruptive to my thought-flow
when I am writing something down at the keyboard.

Using Emacs with the LSP server for TypeScript gives me most of the
benefits of the VSCode experience, without the hassles of straddling
the "WSL Barrier" and it seems to interface just fine with all of the
other tools, and provide the auto-complete and hints that VSCode
provides.

** Rod Dreher on "The Sacred"
[2024-11-04 Mon 09:59]
Dreher spoke about how he'd idolized his childhood family life,
including place and family and his own father's strength.

Good part of his own father's strength was that his dad's way of
doing things helped him to feel safe in the world growing up,
even though the 1970's were turbulent and could be scary to a
young boy.

The bad part was that he realized that he'd turned his family
and his father into a kind of idol, and he realized that his
own family idolized family and place, too.

they referenced the work of Alasdair McIntyre, a Scottish-Anglo-American
philosopher who write a book called _After Virtue_...

Elizabeth Oldfield found the concluding paragraph of later editions
of McIntyre's book After Virtue to be inspiring; faith-community
in the city of London, UK; there's a strong desire amongst Christians
to "pull the ripcord" and escape from a city-setting;

But, says Oldfield, some of us Christians, at least, need to be the
people who serve their cities, by being a separate, distinct community
embedded within the "secular city."  So, it is an "urbanized Benedict
Option" kind of an approach; Dreher says that some people are made for
city living, others for "country/rural living..."

Dreher seems to notice that being a neighbor and inviting people into
your home, even when you live in a city, matters greatly (echoes,
resonances, with _The Gospel Comes with a Housekey_, etc.)

"Withdrawing-from-the-world so we can be Christ-for-the-world in an
authentic way..."

He spoke of the Benedicting monastery:  if we don't close our doors
at night and go and pray and worship together, then we can't be
here for the people who come to us...

So, there's a withdrawing for a time, and then "going forth," too...

Dreher's change to Eastern Orthodoxy:  happened in 2006.
He and his wife believed that Eastern Church was also authentic,
since they were devout Catholics; they held "overwhelming fear and
anger" towards the Catholic church; they felt that the Eastern
church they visited actually took the "real presence" of Christ
in the Lord's Supper seriously; there's this desire from people for
the sense of the transcendant.

Covid-era visitors to their Eastern church in Baton Rouge:  EO
has stood the test of time; the saints:  rich tradition of the saints;
covid frightened these people coming from other protestant churches
(e.g., SBC?) brought them to visit the EO church.

He visited the church/monastery in Chartres where Benedictine Order was
founded?

Old man who was a Monsignor talked of the miracles he witnessed and
which brought him out of atheism...

"Encounter with beauty and then radical goodness..."  this is what
attracts people to the "wonder" and the transcendance...

He spoke later of "morally complicated people" and how "it's better
to look at how you *act* than how you *do*..."

Dreher also remarked that his writing and his in-person conversation
do "hit differently," and he laments this; he seems to be apologetic
about this, about how he comes across as more strident in writing
than he does in person.

[2024-11-04 Mon 12:14] ANOTHER THOUGHT:
Regarding politics, political theology, and the rights of the sojourner:
At the institution of the Passover, in Exodus 12, the LORD instructs
Moses and Aaron about the "stranger" who "shall sojourn with you" and
how he or she can participate and "keep the Passover to the LORD."
The LORD's concluding remark is, "There shall be one law for the
native and for the stranger who sojourns among you." (Ex. 12.49)

This comes at the event of the Exodus, the pivotal salvation-event of
the Old Testament, which, for us as Christian believers, is also the
astonishing, majestic, and wondrous foreshadowing of the work of the
Lord Jesus on the cross to save sinners like us!  And the LORD
declares that the same standard must apply for the "native and for the
stranger who sojourns among you."

It seems to me that politicians of a more leftist sort try to
manipulate Christians who rightly are concerned about the rights of
the sojourner.  At the same time, people who are "in the thick of it"
raise the objection that there is a double standard, and that the
sojourner is not held to the same standard as they.

I think this is what Mr. Dreher may be trying to point us towards: it
is good to take in the vulnerable, and to try to help, but the same
standard, the same "one law for the native and the stranger who
sojourns among you," must apply and be maintained by the magistrate,
the governmental authority.

Elizabeth Oldfield's struggling with the possibility that it is okay
to vote

Other references in the Torah:
 Leviticus 19:34 - You shall treat the stranger who sojourns with you
 as the native among you, and you shall love him as yourself, for you
 were strangers in the land of Egypt: I am the LORD your God.

 Read through Lev. 19.9-10, and then see how it leads into
 the following passages:  Lev. 19.18, 19.33-37; Deut 10.18.

[Need to enumerate all of the uses of the word "sojourner" in the
Torah, as a jumping-off-point for all of this...  the point seems
to be that the proper, non-discriminatory, equal treatment under
God's law is a reflection of the LORD God and his character, and that
the LORD did not see this as an "optional" thing to be applied only
and where *we* feel it is fair.  Additionally, an implication of this
is that there should be consequences for leaders who fail to equally
apply the legal standard to the "sojourner" and "native" alike.]

** struggling to write a comment:
[2024-11-04 Mon 13:19]
Regarding tensions over political theology:
As a Christian of protestant stripe, I must continually refer back to
the standard of God and his Word.  I think, and pray, that you have
the same high view of God's word, and what it has to say about his
character, and our desperate need for a Redeemer: without Christ's
completed work on the cross, we have no hope, and are without God in
the world (cf. Ephesians 2.)

I must also admit to speaking from a North American perspective; in
what follows, I am speaking from my own experience and about what we
see and hear in the US.

At the institution of the Passover, in Exodus 12, the LORD instructs
Moses and Aaron about the "stranger" who "shall sojourn with you" and
how he or she can participate and "keep the Passover to the LORD."
The LORD's concluding remark is, "There shall be one law for the
native and for the stranger who sojourns among you." (Ex. 12.49)

This comes at the event of the Exodus, the pivotal salvation-event of
the Old Testament, which, for us as Christian believers, is also the
astonishing, majestic, and wondrous foreshadowing of the work of the
Lord Jesus on the cross to save sinners like us!  And the LORD
declares that the same standard must apply for the "native and for the
stranger who sojourns among you."

It seems to me that politicians of a more leftist sort, here in the
USA, try to manipulate Christians who rightly are concerned about the
rights of the sojourner.  These politicians sometimes try to accuse
Christians of being racist and refusing to live consistently with
Christian doctrine about caring for neighbor, etc, when objections
about certain immigration policies are raised.

Could this be (at least a part of) what Mr. Dreher may be trying to
point us towards?  It is good and right to take in the vulnerable, and
to try to help, but the same standard, the same "one law for the
native and the stranger who sojourns among you," must apply and be
maintained by the magistrate, the governmental authority.

There are no easy answers here:
US immigration law is a mess.  This makes it unnecessarily difficult
and expensive to legally become a US citizen.  If we want to turn our
(often hard-of-hearing) ears towards the heart of the LORD God about
this, then I am afraid we will find that the LORD also hates it when
we make laws and rules so complicated that we end up giving an unjust
advantage to the wealthy!  Therefore we need Christian leaders to roll
up their sleeves and wade into the mess that is US Immigration Law and
clean it up, write new laws, reform that system.  It might require a
"Wilberforcian" kind of lifetime effort (perhaps hearkening us back to
the willingness-to-suffer Dreher referred to.)

At the same time, it is also absolutely counter to the character and
heart of the LORD God that crimes committed by sojourners are ignored.
This seems to be the kind of problem that has people so angry in the
USA: crimes committed by people who flock to so-called "sanctuary
cities" in the US go unprosecuted.  There are instances of rape and
murder, and when the crimes go unprosecuted, this is also an injustice
which the LORD finds repugnant: this is also a sin which deserves his
wrath, no?

There are other issues as well: periodically, I hear of local school
systems being overwhelmed by a massive influx of children who need
remedial education in English, etc, because they have been allowed in
by (presumably) well-meaning politicians who ignored the cries for
restraint and pleas for time to plan and fund extra remedial efforts.
How can an unprepared school system do the right thing for the
children of sojourners when they are not allowed to prepare?  In what
possible interpretation of Christian teaching is this to be construed
as "caring for the vulnerable?"

All this to say that Christians must dive in and work to address the
legal system, the policy structure, and also call their fellow
followers-ofJesus to engage, and care for the sojourner who crosses
their path, and also to be magistrates/judges/officials who try to
apply "one law for the native and for the stranger who sojourns among
you."
