
* Declarative Languages for web:
** CSS FUNDAMENTALS
Need some kind of review of CSS;
it's an entire rabbit hole unto itself...
*** Class attributes:
Apparently, more than one class attribute can be assigned to
an HTML page element, as in:
<li class="cell cell01"></li>
defining a "list item" element with class attributes of "cell" and "cell01"?
** HTML FUNDAMENTALS
Yet another rabbit hole...


* Procedural Languages for web:
** JavaScript
*** modules
**** import-ing
**** export-ing
*** var, let, const and variable scopes
**** var means it's a "global" scope variable
**** let means it's a "local-to-enclosing-block" variable
**** MOST of the time you want to use let 
***** certainly when it's a variable local-to-a-block
***** Use it in the "global" scope when you'd like to redefine it?
NO:  actually, a "let" used at the "top" level is fundamentally
equivalent to use of "var" correct?
**** scope control for variables
**** variable "hoisting"
Refers to the "legality" and "presence" of a variable
being pushed to the top of its enclosing program block;
https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#variable_hoisting
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#function_hoisting

I seem to recall people talking about "hoisting" in
terms of "function hoisting," in which the identifier
gets "pushed" or "hoisted" up to the "top," when the
identifier names a *function*.  On the other hand,
*variable hoisting* seems to be different affair
entirely.

The use of the term "hoisting" seems to be a particular
artifact of the JavaScript programming language design.
Other languages are much more straightforward, and
issues of identifier scope are simpler.

Note:  from the top of an enclosing block, until the
declaration of a block-level variable, the variable's
value is "undefined," even though the variable exists.
(Got that?)  Attempts to use the variable in the
program block 
See also:  "temporal dead zone."
**** "temporal dead zone"
Refers to the subprogram space between the start of an enclosing
block and the definition of a variable (via declaration?)
and in which the variable can't legally be used in a program,
btw you're not even allowed to try and compare the variable to
"undefined" in the "temporal dead zone!"
***** EXAMPLE
The following:
  var myFifteen = 15;

  { let myFifteen = 14; console.log(myFifteen); }

  { console.log(myFifteen); let myFifteen = 14 }

  console.log(myFifteen);
results in:
  14
  Uncaught ReferenceError: Cannot access 'myFifteen' before initialization
because we don't even get to the final console.log(myFifteen) because
the second block results in that "Uncaught ReferenceError."
So, no use of variables which haven't been declared yet, even to
see if they're 'undefined...'

However:
  var myFifteen=15;
  { let fcn = function () {console.log(myFifteen);}; let myFifteen=14; fcn(); }
  console.log(myFifteen)
results in:
  14
  15
because that block's call to its locally-defined function, bound to
the name "fcn", uses the local-to-block instance of the variable myFifteen,
which is bound to the value 14 by the let-assignment, and by the time
the function-named-by-fcn is invoked, that let-binding is in effect.

And this completes without an uncaught ReferenceError:
  var myFifteen=15;
  { let myFifteen; let fcn = function() {console.log(myFifteen);};
    if (myFifteen == undefined) console.log("It's undefined!"); else console.log(myFifteen) ;
    myFifteen=14; fcn(); }
  console.log(myFifteen)
Its output:
  It's undefined!
  14
  15

*** comparison operators
i.e., == versus =​=​=
**** AN EMACS ORG-MODE NOTE:
(N.B. there is a non-breaking space, 200B, between
those final two equal-signs...
inserted via:
  C-x 8 <RET> 200B <RET>
It seems, after looking at it with hexl-mode, that there's
further encoding done of "0x200b" into something else,
because I do NOT see a sequence of 0B20 or something of
the sort inside the hexl-mode view of this file!
This is necessary because in org mode, a double-equals sign
delimits something which should be rendered as bold-face text
or some such...)

**** the difference between the two:
<A> =​= <B> is, roughly,
"see if <A> evaluates to something equal to what <B> evaluates into,
given JavaScript's peculiar variable and equality rules."

While the =​== is, roughtly,
"see if <A> =​= <B> and also if <A> and <B> are the same type."
(what ever "type" means in Javascript...)

So, for example:
  14 =​= "14"
is true, but
  14 =​=​= "14"
is false.

*** objects
More like "structures" or "records" or like Python's "dictionary"
*** classes
**** inheritance
**** overriding?
Does Javascript provide dynamic dispatch for overridden methods?
It seems this is possible, but the introductory course doesn't
really talk much about it such issues.
*** DOM changes via JavaScript
**** Emphases in Morten Rand-Hendricksen JavaScript Course:
***** DOM-manipulation
The Morten Rand-Hendricksen course on JavaScript did lots to
fiddle with the styles assigned to individual page elements by
simply mutating via assignments like:
  <element-item>.style.<style-attribute> = <some-value>;
and other such mutations.
***** iteration:
Iteration over collections of page elements fetched via
  document.querySelectorAll('<CSS-STYLE-SPECIFICATION>')
(or the querySelector method, also)
was often shown to demonstrate how to walk through a pile of
stuff on a page and change how it looks.  This was a mechanism
to allow one to find everything on the page which meets certain
criteria, and changing it in specified ways.  When we have
decided ahead of time that a certain set of page elements should
have certain styles, this gives us a way to manipulate a set
of page elements as a unit...
**** document.querySelector
**** document.querySelectorAll('<STYLE-SPECIFICATION>')
What ain't terribly clear is how to write the <STYLE-SPECIFICATION>, eh?
**** iterating over DOM elements seems to be a recurring theme!
*** Array methods
**** map
**** reduce


*** Peculiar:  Destructuring assignment

**** Particular examples are shown in
09_05/script.js saved in the main-personal branch.
**** One example
An example:
let myObject = { first: 'firstval', key : 14, active: false };
// And now, within the scope of a function, we "pull out" the elements/properties
// of myObject, which is accessible from within the function body:
(function() {
  let {first: first , active: active} = myObject;
  // And now, inside this function,
  // identifier
  //   first
  // is bound to
  //   myObject.first
  // and myObject.first == 'firstval',
  // and also, identifier
  //   active
  // is bound to myObject.active.
  //
  console.log(`${first} , ${active}`)
 } ) ();
// This outputs to console:
//   firstval , false
*** setting up NPM for use on your workstation
see file runtime-setup-notes.txt
*** node-ecosystem
**** package.json
**** npm commands
***** npm install
***** npm install <MODULE-NAME>

** TypeScript

*** This is mandated by Oracle web stuff nowadays!

*** TypeScript Essentials LinkedIn Learning Notes

**** installation

***** Install at the "project level"
This sets it up as a "dev dependency" so that it does not
end up installed "globally for the entire machine,"
and allows you to change to different flavors/versions of
typescript for each distinct project.  Installing as a
"dev dependency" also means that typescript will only be
needed at development time, and not used by your application
at runtime:
  npm install typescript --save-dev
If you want it installed for the "entire machine," or
"globally" then use the command:
  npm install typescript -g

Therefore, I may need to execute the
  npm install typescript --save-dev
for each lesson folder in the LinkedIn course?

***** Special note on use for the LinkedIn course:
I installed the typescript system at the top of the
repo cloned from the instructor, which is 3 hops above
the individual exercise file directory.  That is, in
the top-level folder of the repository, I used:
  npm install typescript --save-dev
and from there, I could change to subordinate folder
  cd exercise_files/Ch01/01_03b
and execute:
  npx tsc
and it should build things appropriately.  One may use the
--listFilesOnly option for the typescript compiler and
have it vomit out all of the files it examines in order
to do a "build," which is useful when trying to
troubleshoot what the course materials are doing.

What's more, the instructor is fond of shutting OFF the
"emitting javascript" option so that no new output files are
generated, via a tsconfig.json file, and so that "noEmit"
in the compilerOptions of the tsconfig.json file may need
to be fiddled with also.

** Oracle JET needs 

*** TypeScript

*** Nodejs

*** NPM

*** Preact
Oracle made use of this and their JET documentation is
bifurcated into the "virtual DOM" and "MVVM" thinking...

* understanding Javascript for long-term in Oracle Cloud Fusion
Need to understand the rest of Javascript as quickly as possible, and then
get to where we understand how to use it to program with Oracle's JET?
Need to know if "Visual Builder" applications are actually node-based
applications which can be run inside a node application server,
and which can be run on something other than Oracle's infrastructure.

This ain't necessarily a bad thing, just a different thing.
But not being allowed to run SQL in the way which we used to
is going to be a major change for some folks on our team,
and could become a big hurdle to overcome.

* long-term thoughts about programming:
If there is some hope, it might lie with the Plato programming
language, by Christopher Diggins, and improved automation of the AEC
world-of-business-operations.

Architecture, Engineering, and Construction businesses need further
help, and Diggins, a former Microsoft guy, started a consultancy
to develop software and services for AEC firms.  Read more at:
  https://ara3d.com/ his firm's website
  https://github.com/cdiggins his github profile
Diggins designed a concatenative programming language called
Cat, which was forth-like language which also had type inference,
so it was a concatenative, strongly-typed, functional programming
language.



* WSL kind of sucks
WSL is barely adequate as a Linux environment:  there are
enought quirks and irregularities that one pines for a
standard, atop-the-metal Linux environment, in the best
of circumstances.  That is, even when the host Windows system
is not hobbled/encumbered with lots of extra mandated
"infrastructure/gunk," WSL has all kinds of problems.  The
only reasonable thing is that Microsoft is, to a degree,
"forced" to deal with its problems, even if the fix you
keenly need to deal with your particular vexing problem
seems to be low on Microsoft's priority list!

When Windows-underneath is further hobbled with inadequately-
configured "security-protections" (invasive things like
BeyondTrust and/or Crowdstrike) then WSL is just worse,
and the host Windows system is so terribly hobbled that
WSL can't work well:  for example, there isn't enough RAM
left to allow it to function well and operate properly.

This can tend to make WSL sound like a reasonable solution
to certain classes of problems, until the ugly reality of
severely curtailed and limited RAM kicks some teeth out
and one realizes that the imposed "security" solutions
render practical use of WSL impossible.

